/** Source-only diagnostic. Never synthesizes a Claude identity or billing marker. */
import http from "node:http";
import https from "node:https";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { probeHeaders } from "./credentials.js";
import { nativeProcess, isolatedNativeEnv } from "./native-process.js";
import { object } from "./probe.js";
import { createSseParser } from "../../src/codex-response.js";
import { filterRawHeaders, setRawRequestHeaders, HOP_BY_HOP, RESPONSE_STRIP } from "../../src/raw-http-passthrough.js";

const PROMPT = "Reply with exactly gate-ok.";
const MAX_BYTES = 2 * 1024 * 1024;
type Item = Record<string, unknown>;
export interface NativeClaudeCapture { path: string; rawHeaders: string[]; body: Item }
interface Observation {
  variant: string; httpStatus: number; completed: boolean; gateReply: boolean;
  genericRateLimit: boolean; retryAfterPresent: boolean; textCharacters: number; endedTurn: boolean;
}

async function boundedBytes(message: http.IncomingMessage): Promise<Buffer> {
  const chunks: Buffer[] = []; let bytes = 0;
  for await (const chunk of message) {
    bytes += chunk.length;
    if (bytes > MAX_BYTES) { message.destroy(); throw new Error("body_limit"); }
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
}

/** Run a bounded experiment using a request generated by an isolated native client. */
export async function withNativeClaudeCapture<T>(experiment: (capture: NativeClaudeCapture, headers: Record<string, string>) => Promise<T>): Promise<T> {
  const headers = await probeHeaders({ provider: "claude", auth: "subscription" });
  const pending = new Set<http.ClientRequest>();
  let capture: NativeClaudeCapture | undefined;
  let requests = 0;
  const send = (path: string, rawHeaders: string[], body: Buffer, reply: (response: http.IncomingMessage) => void) => {
    const outgoing = https.request({ hostname: "api.anthropic.com", path, method: "POST",
      signal: AbortSignal.timeout(30000) }, reply);
    pending.add(outgoing);
    outgoing.on("close", () => pending.delete(outgoing));
    setRawRequestHeaders(outgoing, filterRawHeaders(rawHeaders, HOP_BY_HOP));
    outgoing.end(body);
    return outgoing;
  };
  const relay = http.createServer(async (req, res) => {
    try {
      if (req.method !== "POST" || !/^\/v1\/messages(?:\?|$)/.test(req.url ?? "") || ++requests > 4) {
        res.writeHead(404); res.end(); return;
      }
      const raw = await boundedBytes(req);
      const body = object(JSON.parse(raw.toString("utf8")));
      const outgoing = send(req.url!, req.rawHeaders, raw, response => {
        if (!capture && response.statusCode === 200 && body?.["model"] === "claude-sonnet-5" &&
          body["stream"] === true && typeof body["max_tokens"] === "number" && body["max_tokens"] >= 128 &&
          JSON.stringify(body["messages"])?.includes(PROMPT)) {
          capture = { path: req.url!, rawHeaders: [...req.rawHeaders], body };
        }
        res.writeHead(response.statusCode ?? 502, filterRawHeaders(response.rawHeaders, RESPONSE_STRIP));
        response.pipe(res);
      });
      outgoing.on("error", () => { if (!res.headersSent) res.writeHead(502); res.end(); });
    } catch { if (!res.headersSent) res.writeHead(400); res.end(); }
  });
  let temp: string | undefined;
  try {
    temp = await mkdtemp(join(tmpdir(), "subswitch-system-control-"));
    const work = join(temp, "work"), config = join(temp, "config");
    await mkdir(work, { mode: 0o700 }); await mkdir(config, { mode: 0o700 });
    await new Promise<void>((resolve, reject) => {
      relay.once("error", reject); relay.listen(0, "127.0.0.1", resolve);
    });
    const address = relay.address();
    if (!address || typeof address === "string") throw new Error("listen_failed");
    const native = await nativeProcess("claude", [
      "--print", "--setting-sources", "", "--settings", '{"disableAllHooks":true}',
      "--disable-slash-commands", "--strict-mcp-config", "--no-session-persistence",
      "--tools", "", "--permission-mode", "dontAsk", "--model", "claude-sonnet-5",
      "--output-format", "json", PROMPT,
    ], { cwd: work, env: isolatedNativeEnv({ CLAUDE_CONFIG_DIR: config,
      CLAUDE_CODE_OAUTH_TOKEN: headers["authorization"]!.slice("Bearer ".length),
      ANTHROPIC_BASE_URL: `http://127.0.0.1:${address.port}` }), timeoutMs: 45000 });
    const answer = object(JSON.parse(native.stdout));
    if (native.code !== 0 || native.failure || answer?.["is_error"] !== false ||
      typeof answer["result"] !== "string" || !answer["result"].includes("gate-ok") || !capture) {
      throw new Error("native_control_failed");
    }

    return await experiment(capture, headers);
  } finally {
    capture = undefined;
    for (const outgoing of pending) outgoing.destroy();
    relay.closeAllConnections();
    await new Promise<void>(resolve => relay.close(() => resolve()));
    if (temp) await rm(temp, { recursive: true, force: true });
  }
}

/** Reproduce the identity-sensitive rejection, not the reverse provider acceptance gate. */
export async function runClaudeSystemControl() {
  return withNativeClaudeCapture(async (capture, headers) => {
    const send = (path: string, rawHeaders: string[], body: Buffer, reply: (response: http.IncomingMessage) => void) => {
      const outgoing = https.request({ hostname: "api.anthropic.com", path, method: "POST", signal: AbortSignal.timeout(30000) }, reply);
      setRawRequestHeaders(outgoing, filterRawHeaders(rawHeaders, HOP_BY_HOP));
      outgoing.end(body);
      return outgoing;
    };
    // Keep only our ordinary probe headers and the native feature-beta selection.
    // In particular, retain our SubSwitch user-agent, with no x-app or SDK fingerprint.
    let beta: string | undefined;
    for (let i = 0; i < capture.rawHeaders.length; i += 2) {
      if (capture.rawHeaders[i]!.toLowerCase() === "anthropic-beta") beta = capture.rawHeaders[i + 1];
    }
    if (!beta || !Array.isArray(capture.body["system"])) throw new Error("native_shape_changed");
    if (Array.isArray(capture.body["tools"]) && capture.body["tools"].length) throw new Error("unexpected_tools");
    const system = capture.body["system"] as unknown[];
    const billing = (value: unknown) => typeof object(value)?.["text"] === "string" &&
      (object(value)!["text"] as string).startsWith("x-anthropic-billing-header:");
    const identity = (value: unknown) => typeof object(value)?.["text"] === "string" &&
      /^(You are Claude Code,|You are a Claude agent,)/.test(object(value)!["text"] as string);
    if (system.filter(billing).length !== 1 || system.filter(identity).length !== 1) {
      throw new Error("native_system_shape_changed");
    }
    const retained: Item = { ...capture.body, system: system.filter(value => !billing(value)) };
    delete retained["metadata"];
    const removed: Item = { ...retained, system: (retained["system"] as unknown[]).filter(value => !identity(value)) };
    const rawHeaders = Object.entries({ ...headers, "anthropic-beta": beta }).flat();
    const path = capture.path;
    const probe = (variant: string, body: Item): Promise<Observation> => new Promise((resolve, reject) => {
      const outgoing = send(path, rawHeaders, Buffer.from(JSON.stringify(body)), response => {
        void (async () => {
          // Our headers do not request compression. Fail explicitly if the server changes that contract.
          if (response.headers["content-encoding"]) { response.destroy(); throw new Error("unexpected_encoding"); }
          const bytes = await boundedBytes(response);
          let parsed: Item | undefined;
          let text = "", stopped = false, failed = false, endedTurn = false;
          if (/text\/event-stream/i.test(String(response.headers["content-type"]))) {
            const parser = createSseParser(MAX_BYTES); parser.end(bytes);
            for await (const frame of parser) {
              if (!frame.data || frame.data === "[DONE]") continue;
              const event = object(JSON.parse(frame.data));
              const delta = object(event?.["delta"]);
              const block = object(event?.["content_block"]);
              if (event?.["type"] === "content_block_start" && block?.["type"] === "text" &&
                typeof block["text"] === "string") text += block["text"];
              if (event?.["type"] === "content_block_delta" && delta?.["type"] === "text_delta" &&
                typeof delta["text"] === "string") text += delta["text"];
              if (event?.["type"] === "message_stop") stopped = true;
              if (event?.["type"] === "error") failed = true;
              if (event?.["type"] === "message_delta" && delta?.["stop_reason"] === "end_turn") endedTurn = true;
            }
          } else parsed = object(JSON.parse(bytes.toString("utf8")));
          const error = object(parsed?.["error"]);
          resolve({ variant, httpStatus: response.statusCode ?? 0, completed: stopped && !failed,
            textCharacters: text.length, endedTurn,
            gateReply: text.includes("gate-ok"), retryAfterPresent: response.headers["retry-after"] !== undefined,
            genericRateLimit: response.statusCode === 429 && error?.["type"] === "rate_limit_error" && error["message"] === "Error" });
        })().catch(reject);
      });
      outgoing.on("error", reject);
    });
    const results = [await probe("native_identity_retained", retained)];
    // This diagnoses acceptance, not exact task following: retain gateReply separately.
    // Require real text and an end_turn terminal; 200 alone or a truncated response is insufficient.
    const passed = (result: Observation) => result.httpStatus === 200 && result.completed && result.endedTurn && result.textCharacters > 0;
    if (passed(results[0]!)) {
      results.push(await probe("native_identity_removed", removed));
      // Restore the same native-generated request to rule out a transient quota transition.
      // This is a paired diagnostic control, not automatic inference retry or billing fallback.
      results.push(await probe("native_identity_retained_again", retained));
    }
    return { schemaVersion: 1, nativeControl: true,
      capturedMaxTokens: capture.body["max_tokens"],
      reproduced: results.length === 3 && passed(results[0]!) && results[1]!.genericRateLimit && passed(results[2]!),
      reverseGatePassed: false, results };
  });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const report = await runClaudeSystemControl();
    console.log(JSON.stringify(report)); process.exitCode = report.reproduced ? 0 : 1;
  } catch { console.log(JSON.stringify({ schemaVersion: 1, reproduced: false, code: "system_control_unavailable" })); process.exitCode = 2; }
}
